In [1]:
import s3fs
import pandas as pd

# Inicializando o sistema de arquivos MinIO
fs = s3fs.S3FileSystem(
    key='ROOT',  # Seu MINIO_ROOT_USER
    secret='PASSWORD',  # Sua MINIO_ROOT_PASSWORD
    client_kwargs={'endpoint_url': 'http://localhost:9000'}
)

# Caminho do bucket e pasta na camada PRATA
bucket_path_prata = 'dados-mercado/PRATA/'

# Listando o arquivo Parquet mais recente na pasta PRATA
parquet_files = fs.glob(f'{bucket_path_prata}*.parquet')
if parquet_files:
    latest_parquet_file = max(parquet_files, key=lambda x: x.split('_')[-1].split('.')[0])
    
    # Lendo o arquivo Parquet em um DataFrame
    with fs.open(latest_parquet_file, 'rb') as f:
        df = pd.read_parquet(f)
        
    # Exibindo os dados do arquivo Parquet da camada PRATA
    print("Dados do arquivo Parquet na camada PRATA:")
    print(df)
else:
    print("Nenhum arquivo Parquet encontrado na camada PRATA.")

df

Dados do arquivo Parquet na camada PRATA:
                            timestamp    id                 nome  \
0    2024-07-12T11:49:27.912206-03:00  7139   Miguel Casa Grande
1    2024-07-12T11:49:27.912206-03:00  7139   Miguel Casa Grande
2    2024-07-12T11:49:27.912206-03:00  7139   Miguel Casa Grande
3    2024-07-12T11:49:27.912299-03:00  7896        Benicio Silva
4    2024-07-12T11:49:27.912299-03:00  7896        Benicio Silva
..                                ...   ...                  ...
146  2024-07-12T15:17:37.959531-03:00  2768     Vinicius Rezende
147  2024-07-12T15:17:37.959558-03:00  1352  Gabriela Montenegro
148  2024-07-12T15:17:37.959558-03:00  1352  Gabriela Montenegro
149  2024-07-12T15:17:37.959558-03:00  1352  Gabriela Montenegro
150  2024-07-12T15:17:37.959558-03:00  1352  Gabriela Montenegro

                       item  preço
0           voluptatibus ex  18.76
1           id voluptatibus   6.64
2                  cum odio  12.90
3    exercitationem dolores   3.23
4              fuga dolorem   9.46
..                      ...    ...
146            ratione nemo   5.43
147             itaque modi   2.55
148             harum totam  13.65
149         nemo laboriosam  11.18
150        temporibus iusto  22.33

[151 rows x 5 columns]

,timestamp,id,nome,item,preço
0,2024-07-12T11:49:27.912206-03:00,7139,Miguel Casa Grande,voluptatibus ex,18.76
1,2024-07-12T11:49:27.912206-03:00,7139,Miguel Casa Grande,id voluptatibus,6.64
2,2024-07-12T11:49:27.912206-03:00,7139,Miguel Casa Grande,cum odio,12.90
3,2024-07-12T11:49:27.912299-03:00,7896,Benicio Silva,exercitationem dolores,3.23
4,2024-07-12T11:49:27.912299-03:00,7896,Benicio Silva,fuga dolorem,9.46
...,...,...,...,...,...
146,2024-07-12T15:17:37.959531-03:00,2768,Vinicius Rezende,ratione nemo,5.43
147,2024-07-12T15:17:37.959558-03:00,1352,Gabriela Montenegro,itaque modi,2.55
148,2024-07-12T15:17:37.959558-03:00,1352,Gabriela Montenegro,harum totam,13.65
149,2024-07-12T15:17:37.959558-03:00,1352,Gabriela Montenegro,nemo laboriosam,11.18
150,2024-07-12T15:17:37.959558-03:00,1352,Gabriela Montenegro,temporibus iusto,22.33